### ISSUE TITLE
Lane Code

### ISSUE THREAD

**Issue by AbhisekOmkar** [SoonerRobotics/igvc_software_2021#12]
What is the directory of the Lanenet code

**Comment by noahzemlin** [comment]
Hi! We performed lane detection in two ways: with HSV thresholding and with a U-Net CNN. Below are the locations for both of those:

- Thresholding (this is what we used at competition): https://github.com/SoonerRobotics/igvc_software_2021/blob/master/igvc_ws/src/igvc_vision/src/CV_to_Map.py
- U-Net CNN: https://github.com/SoonerRobotics/igvc_software_2021/tree/master/cnn/unet_model
